### ISSUE TITLE
Missing import of CreationError in query.py

### ISSUE THREAD

**Issue by markbuckley** [tariqdaouda/pyArango#4]
I think there's a missing import in query.py. Here's an example:
```
from pyArango.connection import *

conn = Connection()
db = conn['_system']
docs = db.AQLQuery("for x in myCollection return { name : x.name }", batchSize = 1);

for doc in docs:
  print doc
```
which gives me
```
Traceback (most recent call last):
  File "c:\Users\z0017wrp\Desktop\kks-decoder\minimalExample.py", line 7, in <module>
    for doc in docs:
  File "build\bdist.win32\egg\pyArango\query.py", line 89, in next
  File "build\bdist.win32\egg\pyArango\query.py", line 106, in __getitem__
  File "build\bdist.win32\egg\pyArango\query.py", line 63, in _developDoc
NameError: global name 'CreationError' is not defined
```
I know that my code does not follow the intended usage of the function `AQLQuery` and that I should be using `rawResult=True`, but it's still better to have the error raised correctly rather than a crash.

Versions: pyArango-1.0.1, Python 2.7.9, ArangoDB 2.6.1, Win7 64 bit.

**Comment by tariqdaouda** [comment]
Thank you for the pull request.
