### ISSUE TITLE
NameError: name 'updateError' is not defined

### ISSUE THREAD

**Issue by zopyx** [tariqdaouda/pyArango#53]
```
>>> db = Database(conn, 'system')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajung/src/lib/python3.5/site-packages/pyArango/database.py", line 34, in __init__
    self.reload()
  File "/Users/ajung/src/lib/python3.5/site-packages/pyArango/database.py", line 80, in reload
    self.reloadCollections()
  File "/Users/ajung/src/lib/python3.5/site-packages/pyArango/database.py", line 62, in reloadCollections
    raise updateError(data["errorMessage"], data)
NameError: name 'updateError' is not defined


```

**Comment by tariqdaouda** [comment]
Hi Zopyx,

This error has been fixed, if you do a git pull it should be ok.
