### ISSUE TITLE
links(...) _id save failure

### ISSUE THREAD

**Issue by remingtonc** [tariqdaouda/pyArango#96]
Using latest master.
```python
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    main()
  File "main.py", line 62, in main
    populate_static(db)
  File "/data/static.py", line 301, in populate_static
    populate_os_releases(db)
  File "/data/static.py", line 292, in populate_os_releases
    db['OSHasRelease'].createEdge().links(new_os, new_release)
  File "/root/.local/share/virtualenvs/data-I7nS9QO2/lib/python3.6/site-packages/pyArango/document.py", line 405, in links
    fromVertice._id.save()
AttributeError: 'NoneType' object has no attribute 'save'
```

**Comment by tariqdaouda** [comment]
Should work now!
